pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'mvn clean test site'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}